version: '3.9'

services:
    node:
        build:
            context: .
            dockerfile: app.Dockerfile
        image: ${COMPOSE_PROJECT_NAME}-node
        user: "1000:1000"
        env_file: .env
        logging:
            options:
                max-size: "100m"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - .:/usr/src/app/:rw

    crawler:
        image: ${COMPOSE_PROJECT_NAME}-node
        command: [ "./etc/run.sh", "crawler" ]
        user: "1000:1000"
        restart: "always"
        env_file: .env
        logging:
            options:
                max-size: "100m"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - .:/usr/src/app/:rw

    api:
        image: ${COMPOSE_PROJECT_NAME}-node
        command: [ "./etc/run.sh", "api" ]
        user: "1000:1000"
        restart: "always"
        env_file: .env
        logging:
            options:
                max-size: "100m"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - $API_PORT:$API_PORT
        volumes:
            - .:/usr/src/app/:rw
