version: '3.9'

networks:
    default:
        driver: bridge
        name: ${COMPOSE_PROJECT_NAME}_default

services:
    db:
        image: mysql:5.7
        user: "1000:1000"
        restart: "always"
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=$DB_NAME
            - MYSQL_USER=$DB_USER
            - MYSQL_PASSWORD=$DB_PASSWORD
        ports:
            - 127.0.0.1:$DB_PORT_EXTERNAL:$DB_PORT
        volumes:
            - ./.db-data:/var/lib/mysql
            - ./etc/mysql.conf.d:/etc/mysql/conf.d

    node:
        build:
            context: .
            dockerfile: app.Dockerfile
        image: ${COMPOSE_PROJECT_NAME}-node
        user: "1000:1000"
        volumes:
            - .:/usr/src/app/:rw

    app_process:
        depends_on:
            - db
        image: ${COMPOSE_PROJECT_NAME}-node
        command: [ "./etc/run.sh", "process" ]
        user: "1000:1000"
        restart: "always"
        env_file: .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - .:/usr/src/app/:rw

    app_api:
        depends_on:
            - db
        image: ${COMPOSE_PROJECT_NAME}-node
        command: [ "./etc/run.sh", "api" ]
        user: "1000:1000"
        restart: "always"
        env_file: .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - $API_PORT:$API_PORT
        volumes:
            - .:/usr/src/app/:rw
